### ISSUE TITLE
KeyError: 'WildtypeProtein'

### ISSUE THREAD

**Issue by xuxue1986** [genome/cancer-genomics-workflow#164]
Hi, 

I meet a new error when I used pvac-seq,  I use :pvacseq run TUMOR.vcf test1 HLA-G*01:09,HLA-E*01:01,H2-IAb NetMHC PickPocket NNalign /home/xuexu/Documents/melanoma_project/neoantigene/IEDB/pvacseq-4.1.0b0/pvacseq/example_data/result4 -e 9,10 

TUMOR.vcf  originally consists of tumor and normal samples, and I use vcftools to seperate them. Then I use pvacseq to meet this error.

Could you help me to work out the problem?
Executing MHC Class I predictions
Converting VCF to TSV
Traceback (most recent call last):
  File "/home/xuexu/miniconda2/envs/snakes/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/home/xuexu/miniconda2/envs/snakes/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/home/xuexu/miniconda2/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/main.py", line 291, in main
    pipeline.execute()
  File "/home/xuexu/miniconda2/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 292, in execute
    self.convert_vcf()
  File "/home/xuexu/miniconda2/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 133, in convert_vcf
    lib.convert_vcf.main(convert_params)
  File "/home/xuexu/miniconda2/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/convert_vcf.py", line 264, in main
    'wildtype_amino_acid_sequence'   : transcript['WildtypeProtein'],
KeyError: 'WildtypeProtein'

**Comment by susannasiebert** [comment]
Hi,

This is the incorrect repository for this issue. Please re-submit your issue to the [pVAC-Seq repository](https://github.com/griffithlab/pVAC-Seq/issues).

Thanks,
Susanna

**Comment by susannasiebert** [comment]
After you split your VCF did you annotate it with VEP? If so, did you download the plugins before running VEP (`pvacseq install_vep_plugins`)?
